version: "3.9"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=${MONGO_URL_DOCKER}
    depends_on:
      - mongo
    volumes:
      - .:/app
    env_file:
      - .env

  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=news-app
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=adminpassword

volumes:
  mongo_data:


