version: "3.9"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo
    volumes:
      - .:/app
    env_file:
      - .env

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=news-app-prod
    command: ["--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30

volumes:
  mongo_data:


